### ISSUE TITLE
`java.lang.NoSuchMethodError` when compiling documentation

### ISSUE THREAD

**Issue by pauldijou** [tpolecat/tut#139]
Hi there,

I'm a bit at lost after merging a PR in the [JWT Scala](https://github.com/pauldijou/jwt-scala) lib.

The project supports several JSON implementations (Play, Json4s, Circe, ...) and each of them follow the [same pattern](https://github.com/pauldijou/jwt-scala/tree/master/json/play-json/src/main/scala): one file with an `object` implementing the main logic. One file with all implicits. And finally, one `package.scala` exposing the implicits.

So far, so good. Each lib has a `tut` markdown file to display samples. But the last PR introduced support for the uPickle lib. All the same as the other ones, all tests are green, using it works fine, but when compiling its [markdown file](https://github.com/pauldijou/jwt-scala/blob/master/docs/src/main/tut/jwt-upickle-jwt-upickle.md), `tut` seems to compile fine but crashes at runtime with the following error:

```
[tut] *** Error reported at ~/projects/jwt-scala/docs/src/main/tut/jwt-upickle-jwt-upickle.md:20
java.lang.NoSuchMethodError: pdi.jwt.package$.jwtUpickleHeaderReader()Lupickle/Types$Reader;
  at pdi.jwt.JwtUpickle$.parseHeader(JwtUpickle.scala:25)
  at pdi.jwt.JwtUpickle$.parseHeader(JwtUpickle.scala:12)
  at pdi.jwt.JwtCore.$anonfun$decodeRawAll$2(Jwt.scala:245)
  at scala.util.Try$.apply(Try.scala:209)
  at pdi.jwt.JwtCore.decodeRawAll(Jwt.scala:243)
  at pdi.jwt.JwtCore.decodeRawAll$(Jwt.scala:243)
  at pdi.jwt.JwtUpickle$.decodeRawAll(JwtUpickle.scala:12)
  at pdi.jwt.JwtJsonCommon.decodeJsonAll(JwtJsonCommon.scala:54)
  at pdi.jwt.JwtJsonCommon.decodeJsonAll$(JwtJsonCommon.scala:53)
  at pdi.jwt.JwtUpickle$.decodeJsonAll(JwtUpickle.scala:12)
  at pdi.jwt.JwtJsonCommon.decodeJson(JwtJsonCommon.scala:96)
  at pdi.jwt.JwtJsonCommon.decodeJson$(JwtJsonCommon.scala:95)
  at pdi.jwt.JwtUpickle$.decodeJson(JwtUpickle.scala:12)
  at pdi.jwt.JwtJsonCommon.decodeJson(JwtJsonCommon.scala:99)
  at pdi.jwt.JwtJsonCommon.decodeJson$(JwtJsonCommon.scala:98)
  at pdi.jwt.JwtUpickle$.decodeJson(JwtUpickle.scala:12)
  ... 116 elided
```

(and several other `java.lang.NoSuchMethodError` following). I don't have an idea what's going on or why it was working with several libs so far and one more broke the build.

I'm looking for any possible help to fix it. I'm open to rethink the architecture of the project if having several `package.scala` with implicits imported together is the root of the problem. Thanks a lot.

**Comment by tpolecat** [comment]
Hm it looks like tut may be running in an environment with a different version of uPickle than the one used to compile your code. tut runs with the same classpath as your test configuration, so you might check there.

**Comment by pauldijou** [comment]
Double checked, cleaned all I could think of, only have one version of uPickle defined in the project, compiled from scratch, still the error on only one markdown file. Wondering if merging all those `package.scala` is causing a problem on the resulting bytecode.

For now, I disabled tut for the breaking markdown file.

**Comment by ceedubs** [comment]
@pauldijou if you do the same thing in the `test:console` REPL of your project without the usage of tut do you see the same error? Since tut just delegates through to the REPL I _suspect_ that it's not the cause of trouble here.
