### ISSUE TITLE
`scribe-2.7.0` binary issues with `tut-0.6.9`

### ISSUE THREAD

**Issue by gvolpe** [tpolecat/tut#244]
Hi Rob,

I'm experiencing a similar issue to https://github.com/outr/scribe/issues/80 but this time compiling against `scala-2.12.7`. It happened when trying to upgrade to `scribe-2.7.0`. 

I have no idea on what's going on here but this time the error is different, just a NPE. If you think it is not related to `tut` I can raise an issue in the `scribe` repo, thanks a lot!

```
[info] Passed: Total 6, Failed 0, Errors 0, Passed 6
[success] Total time: 37 s, completed Dec 3, 2018 10:50:00 AM
[SBT] fs2-redis λ tut
[info] Running tut.TutMain /workspace/oss/fs2-redis/site/src/main/tut /workspace/oss/fs2-redis/site/target/scala-2.12/resource_managed/main/jekyll .*\.(md|markdown|txt|htm|html) -Xmax-classfile-name 80 -deprecation -encoding UTF-8 -feature -Ypartial-unification -language:existentials -language:higherKinds -Xplugin:/home/gvolpe/.ivy2/cache/org.spire-math/kind-projector_2.12/jars/kind-projector_2.12-0.9.9.jar -Xplugin:/home/gvolpe/.ivy2/cache/com.olegpy/better-monadic-for_2.12/jars/better-monadic-for_2.12-0.2.4.jar
[tut] compiling: /workspace/oss/fs2-redis/site/src/main/tut/effects/strings.md
[error] (run-main-0) java.lang.NullPointerException
[error] java.lang.NullPointerException
[error] 	at scala.tools.nsc.Global.exitingTyper(Global.scala:989)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.x$19$lzycompute(IMain.scala:843)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.x$19(IMain.scala:842)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble$lzycompute(IMain.scala:842)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.headerPreamble(IMain.scala:842)
[error] 	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.preamble(IMain.scala:865)
[error] 	at scala.tools.nsc.interpreter.IMain$CodeAssembler.$anonfun$apply$4(IMain.scala:1283)
[error] 	at scala.tools.nsc.interpreter.IMain$CodeAssembler.apply(IMain.scala:1282)
[error] 	at scala.tools.nsc.interpreter.IMain$CodeAssembler.apply$(IMain.scala:1282)
[error] 	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.apply(IMain.scala:855)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:949)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:944)
[error] 	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:602)
[error] 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:591)
[error] 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:563)
[error] 	at tut.Tut$.$anonfun$interp$6(Tut.scala:56)
[error] 	at tut.felix.IO$Primitive.unsafePerformIO(IO.scala:76)
[error] 	at tut.felix.IO$Compute.loop$1(IO.scala:117)
[error] 	at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
[error] 	at tut.felix.Syntax$IOOps.$anonfun$withOut$2(Syntax.scala:34)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at scala.Console$.withOut(Console.scala:163)
[error] 	at tut.felix.Syntax$IOOps.$anonfun$withOut$1(Syntax.scala:34)
[error] 	at tut.felix.IO$Primitive.unsafePerformIO(IO.scala:76)
[error] 	at tut.felix.IO$Compute.loop$1(IO.scala:121)
[error] 	at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
[error] 	at tut.TutMain$.main(TutMain.scala:8)
[error] 	at tut.TutMain.main(TutMain.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:98)
[error] 	at sbt.Run.run0(Run.scala:92)
[error] 	at sbt.Run.execute$1(Run.scala:68)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:80)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:253)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at tut.TutPlugin$.$anonfun$tutOne$1(TutPlugin.scala:149)
[error] 	at scala.util.Success.foreach(Try.scala:249)
[error] 	at tut.TutPlugin$.tutOne(TutPlugin.scala:149)
[error] 	at tut.TutPlugin$.$anonfun$projectSettings$19(TutPlugin.scala:73)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (microsite / tut) Nonzero exit code: 1
[error] Total time: 2 s, completed Dec 3, 2018 10:50:06 AM
```

For more details see the [PR](https://github.com/gvolpe/fs2-redis/pull/41) and [CI logs](https://travis-ci.org/gvolpe/fs2-redis/builds/462528762).

**Comment by tpolecat** [comment]
Rather than doing `tut` can you do `console` and then paste the contents of the Scala blocks into the REPL? It *should* fail in the same way tut is failing because all tut does is feed stuff to `IMain`. If you can reproduce the failure in the REPL then I would open a Scribe issue. If you can't reproduce it outside of Tut I'll take a look.

**Comment by gvolpe** [comment]
I just tried using the REPL. It compiles without any issues. Let me know if I can do something else to better diagnose the problem and thanks again for taking the time!

**Comment by tpolecat** [comment]
I'll do another release with 2.12.7 and sbt 1.2.7 and see if that helps.

**Comment by tpolecat** [comment]
Ok try with tut 0.6.10

**Comment by gvolpe** [comment]
Works like a charm, thanks a lot!

**Comment by tpolecat** [comment]
Confidence high! :-)
