### ISSUE TITLE
Get NPE when trying to follow README instructions

### ISSUE THREAD

**Issue by matthughes** [tpolecat/tut#85]
I added the tut v4.0.0 plugin as directed and have a single file: src/main/tut/Foo.md (note I don't have the leading slash there, but was trying to figure out how to escape the triple backticks:

```
Here is how you add two numbers:

\```tut
1 + 1
\```
```

When I run `tut`, I get this:

```
[info] Running tut.TutMain /Users/mhughes/ccad/development/ipdc/terminal-topology/src/main/tut /Users/mhughes/ccad/development/ipdc/terminal-topology/target/scala-2.11/tut .*\.(md|txt|htm|html) -deprecation -encoding UTF-8 -feature -unchecked -Xfatal-warnings -Xlint -Yno-adapted-args -Ywarn-numeric-widen -Ywarn-value-discard -Xfuture -target:jvm-1.7 -Ywarn-unused-import -Ywarn-infer-any:false
[info] [tut] compiling: /Users/mhughes/tut-test/src/main/tut/Foo.md
[error] Exception in thread "main" java.lang.NullPointerException
[error] 	at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.x$20$lzycompute(IMain.scala:860)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.x$20(IMain.scala:859)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.importsPreamble$lzycompute(IMain.scala:859)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.importsPreamble(IMain.scala:859)
[error] 	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.preamble(IMain.scala:882)
[error] 	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1284)
[error] 	at scala.tools.nsc.interpreter.IMain$CodeAssembler$$anonfun$apply$23.apply(IMain.scala:1283)
[error] 	at scala.tools.nsc.util.package$.stringFromWriter(package.scala:64)
[error] 	at scala.tools.nsc.interpreter.IMain$CodeAssembler$class.apply(IMain.scala:1283)
[error] 	at scala.tools.nsc.interpreter.IMain$Request$Wrapper.apply(IMain.scala:872)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:958)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:953)
[error] 	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:550)
[error] 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:538)
[error] 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:536)
[error] 	at tut.TutMain$$anonfun$interp$1$$anonfun$apply$52$$anonfun$apply$53$$anonfun$apply$54$$anonfun$apply$55.apply(Tut.scala:218)
[error] 	at tut.TutMain$$anonfun$interp$1$$anonfun$apply$52$$anonfun$apply$53$$anonfun$apply$54$$anonfun$apply$55.apply(Tut.scala:218)
[error] 	at tut.Zed$IO$$anonfun$apply$5.apply(Zed.scala:78)
[error] 	at tut.Zed$IO$$anonfun$apply$5.apply(Zed.scala:78)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$IOOps$$anonfun$ensuring$1.apply(Zed.scala:87)
[error] 	at tut.Zed$IOOps$$anonfun$ensuring$1.apply(Zed.scala:87)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$map$1.apply(Zed.scala:30)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$State$$anonfun$flatMap$1.apply(Zed.scala:31)
[error] 	at tut.Zed$IOOps.unsafePerformIO(Zed.scala:88)
[error] 	at tut.TutMain$.main(Tut.scala:75)
[error] 	at tut.TutMain.main(Tut.scala)
```

**Comment by tpolecat** [comment]
Well that's very strange. What version of sbt and scala are you using? Anything potentially weird in your build?

**Comment by swaldman** [comment]
I get the same NPE with tut plugin v0.4.1. The error is dependent upon whether I have

```
fork := true
```

set in `build.sbt`. If I don't set `fork` to true, the problem goes away.

When I do set `fork` to true, I get some extra information about the problem from the file `tut` is trying to generate:

```
For now, just a test of tut.

```scala
scala> println("Hello World!")
[init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/rt.jar(java/lang/Object.class)

Failed to initialize compiler: object scala in compiler mirror not found.
** Note that as of 2.8 scala does not assume use of the java classpath.
** For the old behavior pass -usejavacp to scala, or if using a Settings
** object programatically, settings.usejavacp.value = true.
```

Reading around a bit, it looks like this problem might be addressed by calling a method called `embedDefaults` on the `Settings` object that is passed to the compiler. See this [StackOverflow question](http://stackoverflow.com/questions/27934282/object-scala-in-compiler-mirror-not-found-running-scala-compiler-programatical), [sbt docs](http://www.scala-sbt.org/0.13/docs/Howto-Scala.html) and [further discussion](https://gist.github.com/harrah/404272).

**Comment by tpolecat** [comment]
Ah, interesting. Thanks for tracking it down. I will check it out.

**Comment by tpolecat** [comment]
Seen also by @johnynek 
https://gitter.im/tpolecat/tut?at=5924a22cfcbbe1891c3a4450

**Comment by tpolecat** [comment]
Fix is to add scala-reflect to the `IMain` classpath. See https://github.com/bazelbuild/rules_scala/pull/202#issuecomment-303630038
